name: aggiornamento orario dati campagna change

on:
#  push:
  repository_dispatch:
  schedule:
    - cron:  '13 */4 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Utilizza l'action github checkout@v2, per automatizzare il check-out
      uses: actions/checkout@v2
    - name: lancia aggiornamento
      run: |-
        chmod +x ./script/datiChange.sh
        ./script/datiChange.sh
    - name: Committa e pusha se ci sono variazioni nei dati
      run: |-
        git config user.name "automatico"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "Data e ora aggiornamento: ${timestamp}" || exit 0
        git push
