name: aggiornamento giornaliero commenti change

on:
#  push:
  repository_dispatch:
  schedule:
    - cron:  '0 22 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Utilizza l'action github checkout@v2, per automatizzare il check-out
      uses: actions/checkout@v2
    - name: installa miller
      run: |-
        mkdir -p ~/bin
        cp bin/mlr ~/bin
        cd ~/bin
        chmod +x mlr
    - name: lancia aggiornamento
      run: |-
        export PATH=$PATH:~/bin
        chmod +x ./script/commentiChange.sh
        ./script/commentiChange.sh
    - name: Committa e pusha se ci sono variazioni nei dati
      run: |-
        git config user.name "automatico"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "Data e ora aggiornamento: ${timestamp}" || exit 0
        git push
